#!/usr/bin/env bash
# Customize these in the config file instead of editing them here.

export DEFAULT_CONFIG_INSTALL=(
  # --- Shell ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.aliases.local\" \"\${XDG_CONFIG_HOME}/zsh/.aliases.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.aliases\" \"\${XDG_CONFIG_HOME}/zsh/.aliases\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.xdg.local\" \"\${XDG_CONFIG_HOME}/zsh/.xdg.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zprofile.local\" \"\${XDG_CONFIG_HOME}/zsh/.zprofile.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zprofile\" \"\${XDG_CONFIG_HOME}/zsh/.zprofile\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshenv\" \"\${HOME}/.zshenv\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshrc.local\" \"\${XDG_CONFIG_HOME}/zsh/.zshrc.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshrc\" \"\${XDG_CONFIG_HOME}/zsh/.zshrc\""
  # --- Editor ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/nvim\" \"\${XDG_CONFIG_HOME}/nvim\""
  # --- Terminal ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/ghostty/config.local\" \"\${XDG_CONFIG_HOME}/ghostty/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/ghostty/config\" \"\${XDG_CONFIG_HOME}/ghostty/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/tmux/tmux.conf\" \"\${XDG_CONFIG_HOME}/tmux/tmux.conf\""
  # --- CLI tools ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/bat/config\" \"\${XDG_CONFIG_HOME}/bat/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/btop/btop.conf\" \"\${XDG_CONFIG_HOME}/btop/btop.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/fastfetch/config.jsonc\" \"\${XDG_CONFIG_HOME}/fastfetch/config.jsonc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/fzf/config.sh\" \"\${XDG_CONFIG_HOME}/fzf/config.sh\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/git/config.local\" \"\${XDG_CONFIG_HOME}/git/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/git/config\" \"\${XDG_CONFIG_HOME}/git/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/gnupg/gpg-agent.conf\" \"\${XDG_CONFIG_HOME}/gnupg/gpg-agent.conf\""
  # --- CLI bins ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/dotfriedrice\" \"\${HOME}/.local/bin/dotfriedrice\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/clip-copy\" \"\${HOME}/.local/bin/clip-copy\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/clip-paste\" \"\${HOME}/.local/bin/clip-paste\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/convert\" \"\${HOME}/.local/bin/convert\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-birthday\" \"\${HOME}/.local/bin/dfr-birthday\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-reload-app\" \"\${HOME}/.local/bin/dfr-reload-app\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-theme-set\" \"\${HOME}/.local/bin/dfr-theme-set\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-update-zsh-plugins\" \"\${HOME}/.local/bin/dfr-update-zsh-plugins\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dtags\" \"\${HOME}/.local/bin/dtags\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/gbd\" \"\${HOME}/.local/bin/gbd\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/gd\" \"\${HOME}/.local/bin/gd\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/gl\" \"\${HOME}/.local/bin/gl\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/mkscript\" \"\${HOME}/.local/bin/mkscript\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/monitor\" \"\${HOME}/.local/bin/monitor\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/myip\" \"\${HOME}/.local/bin/myip\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/outdated\" \"\${HOME}/.local/bin/outdated\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/paccache\" \"\${HOME}/.local/bin/paccache\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/pkg\" \"\${HOME}/.local/bin/pkg\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/ppjson\" \"\${HOME}/.local/bin/ppjson\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/pw\" \"\${HOME}/.local/bin/pw\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/rcurl\" \"\${HOME}/.local/bin/rcurl\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/specs\" \"\${HOME}/.local/bin/specs\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/tmux-shell-cmd\" \"\${HOME}/.local/bin/tmux-shell-cmd\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/weather\" \"\${HOME}/.local/bin/weather\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/wotd\" \"\${HOME}/.local/bin/wotd\""
)

export DEFAULT_CONFIG_INSTALL_GUI_LINUX=(
  # --- Desktop environment ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/elephant\" \"\${XDG_CONFIG_HOME}/elephant\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/fontconfig/fonts.conf\" \"\${XDG_CONFIG_HOME}/fontconfig/fonts.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mako/config.local\" \"\${XDG_CONFIG_HOME}/mako/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mako/config\" \"\${XDG_CONFIG_HOME}/mako/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mimeapps.list\" \"\${XDG_CONFIG_HOME}/mimeapps.list\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/niri/config.kdl.local\" \"\${XDG_CONFIG_HOME}/niri/config.kdl.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/niri/config.kdl\" \"\${XDG_CONFIG_HOME}/niri/config.kdl\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/swayidle/config\" \"\${XDG_CONFIG_HOME}/swayidle/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/swaylock/config\" \"\${XDG_CONFIG_HOME}/swaylock/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/uwsm/env\" \"\${XDG_CONFIG_HOME}/uwsm/env\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/walker/config.toml\" \"\${XDG_CONFIG_HOME}/walker/config.toml\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/walker/themes/base/style.css\" \"\${XDG_CONFIG_HOME}/walker/themes/base/style.css\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/waybar/config.jsonc\" \"\${XDG_CONFIG_HOME}/waybar/config.jsonc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/waybar/style.css\" \"\${XDG_CONFIG_HOME}/waybar/style.css\""
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/systemd/system/systemd-networkd-wait-online.service.d/99-network-timeout.conf\" \"/etc/systemd/system/systemd-networkd-wait-online.service.d/99-network-timeout.conf\""
  # --- GUI apps ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mpd/mpd.conf\" \"\${XDG_CONFIG_HOME}/mpd/mpd.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mpv\" \"\${XDG_CONFIG_HOME}/mpv\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/rmpc/config.ron\" \"\${XDG_CONFIG_HOME}/rmpc/config.ron\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/satty/config.toml\" \"\${XDG_CONFIG_HOME}/satty/config.toml\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/tumbler/tumbler.rc\" \"\${XDG_CONFIG_HOME}/tumbler/tumbler.rc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/xarchiver/xarchiverrc\" \"\${XDG_CONFIG_HOME}/xarchiver/xarchiverrc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zathura/zathurarc\" \"\${XDG_CONFIG_HOME}/zathura/zathurarc\""
  # --- GUI data files ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/share/applications/\"* \"\${XDG_DATA_HOME}/applications/\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/share/thumbnailers/mkv.thumbnailer\" \"\${XDG_DATA_HOME}/thumbnailers/mkv.thumbnailer\""
  # --- GUI bins ---
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-clip-paste-on-select\" \"\${HOME}/.local/bin/dfr-clip-paste-on-select\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-first-boot\" \"\${HOME}/.local/bin/dfr-first-boot\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-launch-or-focus\" \"\${HOME}/.local/bin/dfr-launch-or-focus\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-launch-or-focus-tui\" \"\${HOME}/.local/bin/dfr-launch-or-focus-tui\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-menu\" \"\${HOME}/.local/bin/dfr-menu\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-screenshot\" \"\${HOME}/.local/bin/dfr-screenshot\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-theme-set-bg\" \"\${HOME}/.local/bin/dfr-theme-set-bg\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-toggle-notifications\" \"\${HOME}/.local/bin/dfr-toggle-notifications\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/dfr-tz-set\" \"\${HOME}/.local/bin/dfr-tz-set\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/kdenlive\" \"\${HOME}/.local/bin/kdenlive\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/mkclip\" \"\${HOME}/.local/bin/mkclip\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/output-scale\" \"\${HOME}/.local/bin/output-scale\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/rec-start\" \"\${HOME}/.local/bin/rec-start\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/rec-stop\" \"\${HOME}/.local/bin/rec-stop\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/virt-manager\" \"\${HOME}/.local/bin/virt-manager\""
)

export DEFAULT_CONFIG_INSTALL_ARCH=(
  "sudo ln -fns \"/run/systemd/resolve/stub-resolv.conf\" \"/etc/resolv.conf\""
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/conf.d/pacman-contrib\" \"/etc/conf.d/pacman-contrib\""
)

export DEFAULT_CONFIG_INSTALL_WSL=(
  "cp \"\${DOTFRIEDRICE_PATH}/mnt/c/Users/Nick/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json\" \"/mnt/c/Users/%WindowsUser/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json\" || true"
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/wsl.conf\" \"/etc/wsl.conf\""
)