[ids]
*

[global]
overload_tap_timeout = 250

[main]
# 1. Remap CapsLock to:
#    - Tap  -> Escape
#    - Hold -> Meta (The "Super" or "Windows" key)
capslock = overload(meta, esc)

# Remap physical Esc to CapsLock (swap them)
esc = capslock

[shift]
# 2. This makes "Shift + CapsLock" trigger the REAL CapsLock toggle
capslock = capslock
